USE ROLE SECURITYADMIN;

CREATE ROLE FIVETRAN_ROLE;

GRANT ROLE FIVETRAN_ROLE TO ROLE SYSADMIN;

USE ROLE SYSADMIN;

CREATE WAREHOUSE FIVETRAN_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE DATABASE FIVETRAN_DB;

USE DATABASE FIVETRAN_DB;
CREATE SCHEMA RAW;

GRANT USAGE ON WAREHOUSE FIVETRAN_WH TO ROLE FIVETRAN_ROLE;
GRANT USAGE ON DATABASE FIVETRAN_DB TO ROLE FIVETRAN_ROLE;
GRANT USAGE ON SCHEMA FIVETRAN_DB.RAW TO ROLE FIVETRAN_ROLE;
GRANT CREATE TABLE ON SCHEMA FIVETRAN_DB.RAW TO ROLE FIVETRAN_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA FIVETRAN_DB.RAW TO ROLE FIVETRAN_ROLE;

USE ROLE SECURITYADMIN;


CREATE USER FIVETRAN_USER
PASSWORD = '@Jayveer2025'
DEFAULT_ROLE = FIVETRAN_ROLE
DEFAULT_WAREHOUSE = FIVETRAN_WH;

GRANT ROLE FIVETRAN_ROLE TO USER FIVETRAN_USER;

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE FIVETRAN_DB TO ROLE FIVETRAN_ROLE;

GRANT CREATE SCHEMA ON DATABASE FIVETRAN_DB TO ROLE FIVETRAN_ROLE;

USE DATABASE FIVETRAN_DB;

GRANT USAGE ON SCHEMA PUBLIC TO ROLE FIVETRAN_ROLE;

GRANT CREATE STAGE ON SCHEMA PUBLIC TO ROLE FIVETRAN_ROLE;

GRANT CREATE TABLE ON SCHEMA PUBLIC TO ROLE FIVETRAN_ROLE;

GRANT USAGE ON WAREHOUSE FIVETRAN_WH TO ROLE FIVETRAN_ROLE;

USE ROLE FIVETRAN_ROLE;
USE DATABASE FIVETRAN_DB;
USE WAREHOUSE FIVETRAN_WH;

SHOW SCHEMAS;

select * from google_sheets.orders_demo;